FROM apache/airflow:2.9.3-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    git \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Create venv dir with correct permissions
RUN mkdir -p /opt/dbt_venv && chown -R airflow: /opt/dbt_venv

USER airflow

RUN python -m venv /opt/dbt_venv \
  && /opt/dbt_venv/bin/pip install --no-cache-dir --upgrade pip \
  && /opt/dbt_venv/bin/pip install --no-cache-dir \
      dbt-core==1.8.7 \
      dbt-postgres==1.8.2

ENV PATH="/opt/dbt_venv/bin:${PATH}"
