name: spotify_wrapped
version: '1.0.0'
config-version: 2

profile: spotify_wrapped

model-paths:
    [
        'models'
    ]
seed-paths:
    [
        'seeds'
    ]

models:
    spotify_wrapped:
        +materialized: view
