version: 2

models:
    - name: dim_album
      description: "Spotify album dimension with no duplicates"
      columns:
          - name: album_id
            data_type: text
            description:
                "Unique identifier of the album associated with the track,
                as provided in the Spotify data."
            data_tests:
                - not_null
                - unique
          - name: album_name
            data_type: text
            description: "Name of the album as displayed in Spotify."
          - name: album_release_date
            data_type: date
            description: "Album release date in YYYY-MM-DD format."
            data_tests:
                - not_null
          - name: album_total_tracks
            data_type: int
            description: "Number of total tracks on the album"
            data_tests:
                - dbt_utils.expression_is_true:
                      arguments:
                          expression: "album_total_tracks>0"
          - name: album_type
            data_type: text
            description:
                "Type of album release in the Spotify catalog,
                such as album, single or compilation."
            data_tests:
                - not_null
                - accepted_values:
                      arguments:
                          values:
                              [
                                  "single",
                                  "album",
                                  "compilation"
                              ]
    - name: dim_artist
      description: "Spotify artist dimension with no duplicates"
      columns:
          - name: artist_name
            data_type: text
            description: "Artist name displayed as in Spotify"
            data_tests:
                - not_null
                - unique
          - name: artist_followers
            data_type: bigint
            description: "Number of artist followers as displayed in Spotify"
            data_tests:
                - accepted_range:
                      arguments:
                          - min_value: 0
          - name: artist_popularity
            data_type: int
            description:
                "Spotify artist popularity score on a scale 0-100,
                where higher means more popular"
            data_tests:
                - accepted_range:
                      arguments:
                          - min_value: 0
                          - max_value: 100
    - name: dim_track
      description: "Spotify track dimension with no duplicates"
      columns:
          - name: track_id
            data_type: text
            description:
                "Unique identifier of the track
                as provided in the Spotify data."
            data_tests:
                - not_null
                - unique
          - name: track_name
            data_type: text
            description: "Name of the track as displayed in Spotify."
            data_tests:
                - not_null
          - name: track_number
            data_type: int
            description:
            data_tests:
                - accepted_range:
                      arguments:
                          min_value: 1
          - name: track_popularity
            data_type: int
            description: ""
            data_tests:
                - accepted_range:
                  arguments:
                      min_value: 0
                      max_value: 100
          - name: track_duration_min
            data_type: double precision
            description: ""
            data_tests:
                - accepted_range:
                  arguments:
                      min_value: 0
          - name: explicit
            data_type: boolean
            description: ""
            data_tests:
                - dbt_utils.expression_is_true:
                      arguments:
                          expression: "explicit in (true, false)"
